# Generated by Django 4.0.3 on 2022-04-04 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='companyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=200)),
                ('Company_Website', models.CharField(max_length=400)),
                ('Company_Phone_Number', models.CharField(max_length=20)),
                ('Company_Address', models.CharField(max_length=200)),
                ('Company_City', models.CharField(max_length=200)),
                ('Company_State', models.CharField(max_length=200)),
                ('Company_Country', models.CharField(max_length=100)),
                ('Industry_List', models.CharField(choices=[('Account', 'Account'), ('IT', 'IT'), ('Sales', 'Sales'), ('Health Care', 'Health Care')], max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Company_Name'],
            },
        ),
    ]
