# Generated by Django 4.0.3 on 2022-04-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='user',
        ),
    ]
